#title: "STOTEN_NST"
#This files contains NST graphics
#Figure 4
#Figure S4


#Normalized Stochastic Ratio Graphics

#Figure 4: Normalized stochastic ration of baterial community assembly in the bulk soil, rhizosphere soil, and lettuce roo samples with and without antibiotic exposure
```{r}
#Compartment
rm(list=ls())
library(ggplot2)
temporalraw <- read.csv("Yike.bray.NST.boot.summary_compartment.csv",header = TRUE,row.names = 1)
temporalraw <- temporalraw[,4:8]*100
wrapgroup <- c(rep("Shoots",2),rep("Roots",2),rep("Soil",2),rep("Rhizosphere",2))
Treatment <- c("Control","Antibiotics","Control","Antibiotics","Control","Antibiotics","Control","Antibiotics")
temporalraw <- cbind(temporalraw,rownames(temporalraw),wrapgroup,Treatment)
#Remove shoots for low NST
temporalraw <- temporalraw[-c(1:2),]
ROWNAMESNEW <- cbind("Roots_No","Roots_Yes","Soil_No","Soil_Yes","Rhizo_No","Rhizo_Yes")
rownames(temporalraw) <- ROWNAMESNEW

temporalraw$wrapgroup <- factor(x = temporalraw$wrapgroup,levels = c("Soil","Rhizosphere","Roots"))

pd <- position_dodge(0.1)
ggplot(temporalraw, aes(x=rownames(temporalraw), ymin=Min, ymax=Max, lower=Quantile25, middle=Median, upper=Quantile75,fill=Treatment))+
  geom_boxplot(stat='identity')+xlab("Treatment") +
  ylab("Normalized Stochasticity Ratio (NST) (%)") +
  ggtitle("Stochasticity Test") +
  scale_y_continuous(breaks=0:10*10)+                       # Expand y range
  theme_bw() +scale_fill_manual(breaks = c("Antibiotics", "Control"),values=c("red", "blue"))+
  theme(legend.position="top",axis.text=element_text(size=16),axis.title=element_text(size=16),
        plot.title = element_text(size=22, hjust=0.5),text = element_text(size = 16),
        axis.text.x = element_text(angle = 0))+facet_wrap(~wrapgroup,1,scale="free_x")
```



#Figure S4. Normalized stochastic ratio of samples collected on four sampling days
```{r}
rm(list=ls())
library(scales)
library(ggplot2)
setwd("/Users/yikeshen/Desktop/Salmonella_Paper/NST")
temporalraw <- read.csv("Yike.bray.NST.boot.summary_allgroups.csv",header = TRUE,row.names = 1)
temporalraw <- temporalraw[,4:8]*100
wrapgroup <- c(rep("Shoots",8),rep("Roots",8),rep("Soil",8),rep("Rhizosphere",8))
Treatment <- c(rep("Control",4),rep("Antibiotics",4),rep("Control",4),rep("Antibiotics",4),rep("Control",4),
               rep("Antibiotics",4),rep("Control",4),rep("Antibiotics",4))
temporalraw <- cbind(temporalraw,rownames(temporalraw),wrapgroup,Treatment)
temporalraw <- temporalraw[-c(1:8),]
pd <- position_dodge(0.1)
temporalraw$wrapgroup <- factor(x = temporalraw$wrapgroup,levels = c("Soil","Rhizosphere","Roots"))
ggplot(temporalraw, aes(x=rownames(temporalraw), ymin=Min, ymax=Max, lower=Quantile25, middle=Median, upper=Quantile75, fill=Treatment))+
  geom_boxplot(color="black",stat='identity')+xlab("Harvest Day") +
  ylab("Normalized Stochasticity Ratio (NST) (%)") +
  scale_fill_manual(breaks = c("Antibiotics", "Control"),values=c("red", "blue"))+
  ggtitle("Stochasticity Test") +
  scale_y_continuous(breaks=0:10*10)+                       # Expand y range
  theme_bw() +
  theme(legend.position="top",axis.text=element_text(size=16),axis.title=element_text(size=16),
        plot.title = element_text(size=22, hjust=0.5),text = element_text(size = 16),
        axis.text.x = element_text(angle = 90))+facet_wrap(~wrapgroup,1,scales = "free_x")

```

